services:
  restaurante-sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurante-sync
    ports:
      - "5000:5000"
    environment:
      JwtSettings__SecretKey: "00d7662a64f17c621cdf5f89012d83bd3cc2867be5f75dc3e3a920b19c991495508b46ee5f9178dfbefa3a38a18216406602267e6651996ee1cc0a3f119ac42a"
      JwtSettings__Issuer: "RestauranteSync"
      JwtSettings__ExpirationInMinutes: "60"
      JwtSettings__Audience: "RestauranteSyncUsers"
      ConnectionStrings__PostgresConnection: "Host=syncronizer-trasoft-8nrcj4;Port=5432;Database=TrasoftDB;Username=postgres;Password=1-B'GtHyzBl'?)H//LaH"
