services:
  backend:
    build:
      context: .RestauranteSync
      dockerfile: Dockerfile
    container_name: backend_dotnet
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_RUNNING_IN_CONTAINER=true
