[phases.setup]
nixPkgs = ['dotnet-sdk_9']

[phases.build]
cmds = [
    'dotnet restore',
    'dotnet publish -c Release -o out --self-contained false'
]

[phases.start]
cmd = 'dotnet out/TuProyecto.dll'

[variables]
DOTNET_ROOT = '/nix/store/*-dotnet-sdk-9.*/dotnet'