name: Build Docker images
 
on:
  push:
    branches: ["main"]
 
jobs:
  build-and-push-dockerfile-image:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: RestauranteSync/RestauranteSync.API/Dockerfile
          push: true
          # Make sure to replace with your own namespace and repository
          tags: |
            namespace/example:latest 
          platforms: linux/amd64     
